/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedVaultsRouteImport } from './routes/_authenticated/vaults'
import { Route as AuthenticatedTxBuilderRouteImport } from './routes/_authenticated/tx-builder'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReceiveRouteImport } from './routes/_authenticated/receive'
import { Route as AuthenticatedPqLabRouteImport } from './routes/_authenticated/pq-lab'
import { Route as AuthenticatedMultisigRouteImport } from './routes/_authenticated/multisig'
import { Route as AuthenticatedGuardRouteImport } from './routes/_authenticated/guard'
import { Route as AuthenticatedEarnRouteImport } from './routes/_authenticated/earn'
import { Route as AuthenticatedBuyRouteImport } from './routes/_authenticated/buy'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVaultsRoute = AuthenticatedVaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTxBuilderRoute = AuthenticatedTxBuilderRouteImport.update({
  id: '/tx-builder',
  path: '/tx-builder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReceiveRoute = AuthenticatedReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPqLabRoute = AuthenticatedPqLabRouteImport.update({
  id: '/pq-lab',
  path: '/pq-lab',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMultisigRoute = AuthenticatedMultisigRouteImport.update({
  id: '/multisig',
  path: '/multisig',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardRoute = AuthenticatedGuardRouteImport.update({
  id: '/guard',
  path: '/guard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEarnRoute = AuthenticatedEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuyRoute = AuthenticatedBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AuthenticatedAiRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/guard': typeof AuthenticatedGuardRoute
  '/multisig': typeof AuthenticatedMultisigRoute
  '/pq-lab': typeof AuthenticatedPqLabRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/send': typeof AuthenticatedSendRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/tx-builder': typeof AuthenticatedTxBuilderRoute
  '/vaults': typeof AuthenticatedVaultsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AuthenticatedAiRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/guard': typeof AuthenticatedGuardRoute
  '/multisig': typeof AuthenticatedMultisigRoute
  '/pq-lab': typeof AuthenticatedPqLabRoute
  '/receive': typeof AuthenticatedReceiveRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/send': typeof AuthenticatedSendRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/tx-builder': typeof AuthenticatedTxBuilderRoute
  '/vaults': typeof AuthenticatedVaultsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/buy': typeof AuthenticatedBuyRoute
  '/_authenticated/earn': typeof AuthenticatedEarnRoute
  '/_authenticated/guard': typeof AuthenticatedGuardRoute
  '/_authenticated/multisig': typeof AuthenticatedMultisigRoute
  '/_authenticated/pq-lab': typeof AuthenticatedPqLabRoute
  '/_authenticated/receive': typeof AuthenticatedReceiveRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/tx-builder': typeof AuthenticatedTxBuilderRoute
  '/_authenticated/vaults': typeof AuthenticatedVaultsRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/ai'
    | '/buy'
    | '/earn'
    | '/guard'
    | '/multisig'
    | '/pq-lab'
    | '/receive'
    | '/reports'
    | '/send'
    | '/tools'
    | '/tx-builder'
    | '/vaults'
    | '/wallets'
    | '/api/chat'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/ai'
    | '/buy'
    | '/earn'
    | '/guard'
    | '/multisig'
    | '/pq-lab'
    | '/receive'
    | '/reports'
    | '/send'
    | '/tools'
    | '/tx-builder'
    | '/vaults'
    | '/wallets'
    | '/api/chat'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/_authenticated/ai'
    | '/_authenticated/buy'
    | '/_authenticated/earn'
    | '/_authenticated/guard'
    | '/_authenticated/multisig'
    | '/_authenticated/pq-lab'
    | '/_authenticated/receive'
    | '/_authenticated/reports'
    | '/_authenticated/send'
    | '/_authenticated/tools'
    | '/_authenticated/tx-builder'
    | '/_authenticated/vaults'
    | '/_authenticated/wallets'
    | '/api/chat'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vaults': {
      id: '/_authenticated/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof AuthenticatedVaultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tx-builder': {
      id: '/_authenticated/tx-builder'
      path: '/tx-builder'
      fullPath: '/tx-builder'
      preLoaderRoute: typeof AuthenticatedTxBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receive': {
      id: '/_authenticated/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof AuthenticatedReceiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pq-lab': {
      id: '/_authenticated/pq-lab'
      path: '/pq-lab'
      fullPath: '/pq-lab'
      preLoaderRoute: typeof AuthenticatedPqLabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/multisig': {
      id: '/_authenticated/multisig'
      path: '/multisig'
      fullPath: '/multisig'
      preLoaderRoute: typeof AuthenticatedMultisigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guard': {
      id: '/_authenticated/guard'
      path: '/guard'
      fullPath: '/guard'
      preLoaderRoute: typeof AuthenticatedGuardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/earn': {
      id: '/_authenticated/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof AuthenticatedEarnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buy': {
      id: '/_authenticated/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof AuthenticatedBuyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedBuyRoute: typeof AuthenticatedBuyRoute
  AuthenticatedEarnRoute: typeof AuthenticatedEarnRoute
  AuthenticatedGuardRoute: typeof AuthenticatedGuardRoute
  AuthenticatedMultisigRoute: typeof AuthenticatedMultisigRoute
  AuthenticatedPqLabRoute: typeof AuthenticatedPqLabRoute
  AuthenticatedReceiveRoute: typeof AuthenticatedReceiveRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedTxBuilderRoute: typeof AuthenticatedTxBuilderRoute
  AuthenticatedVaultsRoute: typeof AuthenticatedVaultsRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedBuyRoute: AuthenticatedBuyRoute,
  AuthenticatedEarnRoute: AuthenticatedEarnRoute,
  AuthenticatedGuardRoute: AuthenticatedGuardRoute,
  AuthenticatedMultisigRoute: AuthenticatedMultisigRoute,
  AuthenticatedPqLabRoute: AuthenticatedPqLabRoute,
  AuthenticatedReceiveRoute: AuthenticatedReceiveRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedTxBuilderRoute: AuthenticatedTxBuilderRoute,
  AuthenticatedVaultsRoute: AuthenticatedVaultsRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
