// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

const PRODUCTION_SUPABASE_URL = "https://sddeayzumvkdmdgqetyz.supabase.co";
const PRODUCTION_SUPABASE_HOST = "sddeayzumvkdmdgqetyz.supabase.co";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request
        ? input.headers
        : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) =>
        headers.set(key, value),
      );
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function serverEnv(name: "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY") {
  if (typeof process === "undefined" || !process.env) return undefined;
  return process.env[name]?.trim();
}

function createSupabaseClient() {
  // Browser builds must receive the publishable key at build time. SSR/Worker
  // execution may also read the corresponding runtime binding.
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL?.trim() ||
    serverEnv("SUPABASE_URL") ||
    PRODUCTION_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ||
    serverEnv("SUPABASE_PUBLISHABLE_KEY");

  if (!SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "LTCme authentication is not configured: missing Supabase publishable key.",
    );
  }

  let host: string;
  try {
    host = new URL(SUPABASE_URL).hostname;
  } catch {
    throw new Error("LTCme authentication is not configured: invalid Supabase URL.");
  }

  if (host !== PRODUCTION_SUPABASE_HOST) {
    throw new Error(
      `LTCme authentication must use the production Supabase project (${PRODUCTION_SUPABASE_HOST}).`,
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (!_supabase) _supabase = createSupabaseClient();
      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
